### ISSUE TITLE
Move package to MakieOrg

### ISSUE THREAD

**Issue by juliohm** [MakieOrg/SwarmMakie.jl#11]
to help others maintain it: https://github.com/MakieOrg

**Comment by juliohm** [comment]
I would also rename it to `Swarmplots.jl` or `SwarmPlots.jl`, but that is a matter of taste.

**Comment by TheCedarPrince** [comment]
Regarding moving it, that's a good idea! What's your call @asinghvi17 ? I don't have MakieOrg permissions so can't really help here.

**Comment by asinghvi17** [comment]
Sorry I lost track of this - we can definitely move the package to MakieOrg!  I'll have to PR the registry though, so this might take a couple of days to finish.
